development:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: top100_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: top100
  pool: 5
  timeout: 5000

  production:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: top100
  pool: 5
  timeout: 5000